#+TITLE: Normalizzazione forte di $\lambda 2 \mu$
#+STARTUP: latexpreview

Dobbiamo vedere che il sistema $\lambda 2 \mu$ sia fortemente normalizzante, utilizzando la consueta tecnica degli insiemi saturi.
Secondo Geuvers, questo risultato, anche se non presente in letteratura, è simile a quanto dimostrato per un differente sistema di tipi ricorsivi da Mendler nel paper "Inductive types and type constraints in the second-order lambda calculus".

** Review del paper di Mendler

*** Struttura generale della dimostrazione
La dimostrazione si articola in una serie di 6 passi:
**** Definizione di $\Xi$
Detto $\mathsf{T}$ l'insieme dei termini fortemente normalizzabili, definiamo $\Xi$ come un reticolo (insieme parzialmente ordinato in cui ogni coppia di elementi ha sia un estremo inferiore che un estremo superiore) completo (ogni suo sottoinsieme ha sia l’inf che il sup) di sottoinsiemi di $\mathsf{T}$.
I tipi vengono modellati come elementi di $\Xi$.
**** Operazioni che modellano $\rightarrow$, $\Delta$, $\mu$ e $\nu$
Abbiamo già tradotto i tipi nel nostro modello, quindi proseguiamo definendo le operazioni su $\Xi$ che modellano le operazioni sui tipi elencate.
**** Creazione di una funzione di interpretazione
Le operazioni che abbiamo definito sopra ci servono per estendere una funzione $\rho : Var \rightarrow \Xi$, a $\llbracket \cdot \rrbracket \rho : Type \rightarrow \Xi$.
**** Definizione di $\lvert a \rvert$
Qui definiamo cosa intendiamo quando diciamo che il termine non tipato $t$ è sostituto di un termine tipato $a$.
**** Definizione di $\vDash a : A$
Ovvero la nostra nozione di verità sui giudizi di tipo, definita come:
$\vDash a : A \equiv \forall \rho, \forall t, \forall a, t \in \llbracket A \rrbracket \rho$
**** $a$ è fortemente normalizzabile se lo è $\lvert a \rvert$
Da questo si può concludere, perché se $\vdash a:A$ allora $\vDash a : A$, quindi $\lvert a \rvert \in \llbracket A \rrbracket \rho$.
Questo per i primi tre punti implica che $\lvert a \rvert$ sia fortemente normalizzabile, quindi per questo lemma lo è anche $a$.
*** Preliminari
**** Descrizione dei tipi
Iniziamo a descrivere i tipi che useremo nella dimostrazione.
Assumiamo un numero infinito di variabili $V_1, V_2, V_3, \dots$, nel seguito useremo $X,Y,Z$ come metavariabili su di esse.

Definiamo cos'è un tipo:
#+BEGIN_QUOTE
- $X$ è un tipo.
- Se $A$ e $B$ sono tipi, lo sono anche $A \rightarrow B$ e $\Delta X.A$ (notiamo che $\Delta X.A$ è la notazione per l'astrazione sui tipi).
- Se $X$ occorre positivamente in $A$, allora $\mu X.A$ e $\nu X.A$ sono tipi.
#+END_QUOTE

Notiamo che gli operatori $\Delta$, $\mu$ e $\nu$ bindano le occorrenze della variabile a cui si riferiscono.
Possiamo allora definire meglio cosa intendiamo con occorrenze positive e negative:
- $X$ occorre positivamente in $A$, ovvero $Pos(A,X)$ se ogni occorrenza libera di $X$ in $A$ è sul lato sinistro di un numero pari di $\rightarrow$.
- $X$ occorre negativamente in $A$, ovvero $Neg(A,X)$ se ogni occorrenza libera di $X$ in $A$ è sul lato sinistro di un numero dispari di $\rightarrow$.

Come esempio di occorrenze positive e negative, consideriamo gli encoding standard:
$A \times B = \Delta Z. (A \rightarrow B \rightarrow Z) \rightarrow Z$
$A + B = \Delta Z. (A \rightarrow Z) \rightarrow (B \rightarrow Z) \rightarrow Z$
Da cui, contando il numero delle occorrenze sul lato sinistro delle $\rightarrow$, si capisce che una variabile $X$ occorre positivamente in una di queste due formule se occorre positivamente sia in $A$ che in $B$.

Il requisito dell'occorrenza positiva ci interessa perché assicura la monotonicità di certe operazioni sui reticoli completi, e quindi l'esistenza di massimi e minimi punti fissi, che saranno i modelli per i nostri tipi induttivi.

**** Descrizione dei termini tipati
Per ogni termine $\bar{\mu} \equiv \mu X.A$ ho le costanti:
$in^{\bar{\mu}} : A[\bar{\mu}/X] \rightarrow \bar{\mu}$
$R^{\bar{\mu}} : \Delta Y.(\Delta X.(X \rightarrow Y) \rightarrow A \rightarrow Y) \rightarrow \bar{\mu} \rightarrow Y$

La costante $in^{\bar{\mu}}$ ci consente di costruire un termine di tipo $\bar{\mu}$ costruendo un suo unrolling $A[\bar{\mu}/X]$.
La costante $R^{\bar{\mu}}$ è invece un combinatore per l'induzione: dato un tipo $Y$, possiamo costruire una funzione $\bar{\mu} \rightarrow Y$ usando una "ipotesi induttiva" della forma $\Delta X. (X \rightarrow Y) \rightarrow A \rightarrow Y$.
Possiamo pensare a quella funzione come ad una funzione che estende una funzione $X \rightarrow Y$ in una funzione $A \rightarrow Y$.

Dualizzando, per ogni termine $\bar{\nu} \equiv \nu X.A$ ho le costanti:
$out^{\bar{\nu}} : \bar{\nu} \rightarrow A[\bar{\nu}/X]$
$S^{\bar{\nu}} : \Delta Y. (\Delta X. (Y \rightarrow X) \rightarrow Y \rightarrow A) \rightarrow Y \rightarrow \bar{\nu}$

dove $out^{\bar{\nu}}$ rappresenta l'unrolling e $S^{\bar{\nu}}$ è un combinatore per la coinduzione.

**** Regole per l'assegnamento dei tipi:
Abbiamo qui le regole per l'assegnazione dei tipi alle variabili:

\begin{prooftree}
\AxiomC {$$}
\UnaryInfC {$x^A : A$}
\end{prooftree}

Per l'assegnazione dei tipi alle astrazioni, sia su termini che su tipi (nel secondo caso, solo se $X$ non appare libera in $A$ per ogni $x^A$ libero in $B$):

\begin{prooftree}
\AxiomC {$b : B$}
\UnaryInfC {$\lambda x^A.b : A \rightarrow B$}
\end{prooftree}

\begin{prooftree}
\AxiomC {$b : B$}
\UnaryInfC {$\Lambda X.b : \Delta X.B$}
\end{prooftree}

Infine, quelle per l'assegnazione dei tipi alle applicazioni, di nuovo sia per i termini che per i tipi:

\begin{prooftree}
\AxiomC {$c : A \rightarrow B$}
\AxiomC {$a : A$}
\BinaryInfC {$c \: a : B$}
\end{prooftree}

\begin{prooftree}
\AxiomC {$b : \Delta X.B$}
\UnaryInfC {$b \: A : B[A/X]$}
\end{prooftree}

**** Regole di riduzione per i termini tipati
Le prime quattro di queste riduzioni sono le consuete per il lambda-calcolo del secondo ordine;
al solito la seconda e la quarta richiedono rispettivamente che $x^A$ e $X$ non appaiano libere in $a$:

1) $(\lambda x^A.a) \: b \mapsto a[b/x^A]$
2) $\lambda x^A.(a \: x^A) \mapsto a$
3) $(\Lambda X.a) \: B \mapsto a[B/X]$
4) $\Lambda X.(a \: X) \mapsto a$
5) $R^{\bar{\mu}} \: B \: a \: (in^{\bar{\mu}} \: b) \mapsto a \: \bar{\mu} \: (R^{\bar{\mu}} \: B \: a) \: b$
6) $out^{\bar{\nu}}(S^{\bar{\nu}} \: B \: a \: b) \mapsto a \: \bar{\nu} \: (S^{\bar{\nu}} \: B \: a) \: b$

Le ultime due riduzioni riguardano invece i tipi di dato ricorsivi che abbiamo definito:
per la prima, ad esempio, dev'essere:
- $B : Type$
- $a : \Delta X.(X \rightarrow B) \rightarrow A \rightarrow B$
- $in^{\bar{\mu}} \: b : \bar{\mu}$
- $R^{\bar{\mu}} \: B \: a : \bar{\mu} \rightarrow B$

Definiamo anche $a>b$ per dire che $b$ si raggiunge con una sola applicazione di una regola di riduzione ad (un sottotermine di) $a$, mentre con $a >^* b$ intendiamo che $a$ si riduce a $b$ con un numero finito di riduzioni.

*** Un modello di termini non tipati
Costruiamo ora un modello di questo lambda calcolo, mappando tipi in collezioni di termini non tipati.
Nel seguito, indichiamo con $\lvert a \rvert$ il termine non tipato che è ottenuto da $a$ togliendo tutte le annotazioni di tipo.
Quello che rimane saranno le costanti $in$, $out$, $R$, $S$, le variabili non tipate e i termini che formano le operazioni di astrazione e applicazione.
Siano $t$,$u$,$v$ metavariabili per i termini non tipati.
Ereditiamo ovviamente anche delle versioni non tipate delle regole di riduzione:

1) $(\lambda x.t) \: u \mapsto t[u/x]$
2) $\lambda x.(t \: x) \mapsto t$
3) $R \: t \: (in \: u) \mapsto t \: (R \: t) \: u$
4) $out(S \: t \: u) \mapsto t \: (S \: t) \: u$

Manteniamo il significato degli operatori $<$ e $<^{*}$.

Sia adesso $\mathsf{T}$ l'insieme dei lambda-termini non tipati fortemente normalizzanti.
Diciamo che un termine è in ~forma normale esterna (Onf)~ se ha una delle seguenti forme sintattiche: $\lambda x.a$, $R$, $R \: t$, $in$, $in \: t$, $S$, $S \: t$, $S \: t \: u$, $out$.
Notiamo che questo vuol dire che eventuali riduzioni di questi termini si devono applicare per forza a sottoinsiemi propri.
Diciamo che $\xi \subseteq \Xi$ è ~chiuso per riduzione~ se $t \in \xi$ e $t >^* u$ implica che $u \in \xi$.
Diciamo che $\xi \subseteq \Xi$ è ~completo per forma normale esterna~ se per ogni $t \in \xi$, se $t \in \mathsf{T}$ e $u \in Onf$, $t >^{*} u$ implica che $u \in \xi$.
A questo punto possiamo definire $\Xi$ come l'insieme dei sottoinsiemi $\xi \subseteq \mathsf{T}$ che sono sia chiusi per riduzione che completi per forma normale esterna.
Mentre l'essere fortemente normalizzabile e l'essere chiuso per riduzione sembrano subito condizioni molto ragionevoli, la completezza per forma normale esterna è una condizione abbastanza tecnica, e serve in alcuni lemmi.

*** Lemma 1
Questo lemma esprime il fatto che gli elementi di $\Xi$ sono chiusi sotto l'inverso della $\beta$-riduzione.
#+BEGIN_QUOTE
Per $\xi \in \Xi$, $t[u/x] \in \xi$ e $u \in \mathsf{T}$ implicano $(\lambda x.t) \: u \in \xi$
#+END_QUOTE

Per dimostrare questo fatto, vogliamo fare vedere che i termini $(\lambda x.t) \: u$ sono fortemente normalizzabili e completi per riduzione esterna.

**** $t \in \mathsf{T}$
Una sequenza di riduzioni $t = t_0 > t_1 > t_2 > \dots$, sostituendo $u$ per $x$ è una sequenza di riduzioni per $t[u/x]$:
$t[u/x] = t_0[u/x] > t_1[u/x] > t_2[u/x] > \dots$
e sappiamo che questa catena di riduzioni dev'essere finita, perché $t[u/x] \in \mathsf{T}$. Pertanto $t \in \mathsf{T}$.

**** $(\lambda x.t) \: u \in \mathsf{T}$
Sappiamo che $t$ e $u$ sono fortemente normalizzabili.
Allora una riduzione infinita deve contenere una $\beta$ o $\eta$ riduzione al livello più esterno.

Diciamo che sia una beta-riduzione, quindi:
$(\lambda x.t) \: u >^* (\lambda x.t^{\prime}) \: u^{\prime} > t^{\prime}[u^{\prime}/x] > \dots$
con $t >^* t^{\prime}$ e $u >^* u^{\prime}$. Però abbiamo che
$t[u/x] >^* t^{\prime}[u/x] >^* t^{\prime}[u^{\prime}/x]$
quindi $t^{\prime}[u^{\prime}/x]\in \xi \subseteq \mathsf{T}$ per la chiusura. Allora ogni possibile continuazione di questa sequenza è finita.

Diciamo che sia una eta-riduzione, come:
$(\lambda x.t) \: u >^* (\lambda x.t^{\prime\prime} \: x) \: u^{\prime} >^* t^{\prime\prime} \: u^{\prime} > \dots$
dove stavolta $t >^* t^{\prime} = t^{\prime\prime} \: x$ e $u >^* u^{\prime}$. Abbiamo comunque che:
$t[u/x] >^* t^{\prime}[u/x] >^* t^{\prime}[u^{\prime}/x] = t^{\prime\prime} \: u^{\prime}$
che sta in $\xi$ per la relazione di chiusura, e quindi si ha che da quel punto in poi la catena di riduzioni dev'essere finita.

**** Ogni termine $Onf$ a cui $(\lambda x.t) \: u$ riduce è in $\xi$
Supponiamo che $(\lambda x.t) \: u$ riduca ad un termine $v \in Onf$.
Visto che il termine non è in forma normale esterna, nella catena di riduzioni ci dev'essere una $\beta$ o $\eta$ riduzione del livello più esterno.
Abbiamo già visto che in entrambi i casi c'è un termine $t^{\prime}[u^{\prime}/x] \in \xi$ tale che $t^{\prime}[u^{\prime}/x] >^* v$, da cui si conclude per la chiusura.

**** Conclusione
Possiamo concludere che $(\lambda x.t) \: u \in \xi$ grazie ai due punti precedenti.
